### ISSUE TITLE
Don't use content-box for box-sizing.

### ISSUE THREAD

**Issue by mirshko** [3box/profile-hover#83]
Using the default `content-box` `box-sizing` CSS attribute conflicts with the often reset `box-sizing: border-box` property in pretty much all CSS resets.

This causes the ProfileHover component to be all squished like below.

<img width="256" alt="Screen Shot 2020-07-15 at 1 31 23 PM" src="https://user-images.githubusercontent.com/8116716/87540166-7b5ccb00-c69f-11ea-8614-d0fb8a6fabe5.png">

**Comment by oed** [comment]
Nice catch @mirshko! Happy to release this if you create a PR to fix it :)

**Comment by mirshko** [comment]
Dont have bandwidth atm as it will require some styles changes, for now I found a workaround.

wrapping the profile hover class with 

```css
.profileHoverReset *,
.profileHoverReset ::before,
.profileHoverReset ::after {
  box-sizing: content-box;
}
```
